// Builds the throwaway Vite + React harness that renders changed components in
// isolation. Pure: every function returns file {path, content} pairs the caller
// writes under `.anchorage/preview/`. The harness NEVER imports the app's entry
// point — only the changed components (via generated stories under `stories/`),
// so it comes up without the app's auth/data/secret machinery.
//
// Fidelity comes from two things: the repo's global stylesheets are imported
// into the harness, and React is de-duped to the repo's own copy so hooks work
// across the module boundary.

import path from "node:path";
import type { FrontendToolchain } from "./toolchain.js";

export interface HarnessFile {
  /** Path relative to the harness root (.anchorage/preview). */
  path: string;
  content: string;
}

export interface BuildHarnessArgs {
  toolchain: FrontendToolchain;
  /** Absolute path to the repository worktree. */
  workspacePath: string;
  /** Port the harness dev server binds to. */
  port: number;
}

// Harness deps are deliberately minimal — react/react-dom are aliased to the
// repo's copy (see vite.config), so we only need Vite and the React plugin here.
const HARNESS_PACKAGE_JSON = {
  name: "anchorage-preview-harness",
  private: true,
  type: "module",
  scripts: { dev: "vite" },
  devDependencies: {
    vite: "^5.4.0",
    "@vitejs/plugin-react": "^4.3.0",
  },
};

function viteConfig(workspacePath: string, port: number): string {
  // JSON.stringify keeps the absolute paths correctly escaped on every OS.
  const repo = JSON.stringify(workspacePath);
  return `import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";
import path from "node:path";

// The repository worktree. The harness lives at <repo>/.anchorage/preview.
const repo = ${repo};

// https://vitejs.dev/config/ — generated by the Anchorage runtime agent.
export default defineConfig({
  root: __dirname,
  plugins: [react()],
  server: {
    port: ${port},
    host: "0.0.0.0",
    strictPort: false,
    // Allow Vite to read component sources from the repo, not just the harness.
    fs: { allow: [__dirname, repo] },
  },
  resolve: {
    // One React instance only — alias to the repo's copy so component hooks run
    // in the same React as the harness (mismatched copies throw "invalid hook").
    dedupe: ["react", "react-dom"],
    alias: {
      react: path.join(repo, "node_modules/react"),
      "react-dom": path.join(repo, "node_modules/react-dom"),
      // Best-effort support for the common "@/..." -> src alias. Repos that use a
      // different alias resolve via their own tsconfig paths in a later increment.
      "@": path.join(repo, "src"),
    },
  },
});
`;
}

function indexHtml(): string {
  return `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Anchorage · component preview</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.jsx"></script>
  </body>
</html>
`;
}

function mainJsx(globalCssAbsImports: string[]): string {
  const cssImports = globalCssAbsImports.map((p) => `import ${JSON.stringify(p)};`).join("\n");
  return `import React from "react";
import { createRoot } from "react-dom/client";
import { Gallery } from "./gallery.jsx";
${cssImports}

createRoot(document.getElementById("root")).render(<Gallery />);
`;
}

function errorBoundaryJsx(): string {
  return `import React from "react";

// Isolates one card's failure so a single un-renderable component doesn't blank
// the whole gallery — it shows the error inline instead.
export class CardErrorBoundary extends React.Component {
  constructor(props) {
    super(props);
    this.state = { error: null };
  }
  static getDerivedStateFromError(error) {
    return { error };
  }
  render() {
    if (this.state.error) {
      return (
        <pre style={{ margin: 0, padding: 12, color: "#b91c1c", background: "#fef2f2", borderRadius: 8, whiteSpace: "pre-wrap", fontSize: 12 }}>
          {"Couldn't render: " + String(this.state.error?.message ?? this.state.error)}
        </pre>
      );
    }
    return this.props.children;
  }
}
`;
}

function galleryJsx(): string {
  // import.meta.glob auto-discovers every generated story, so the gallery never
  // needs regenerating when the story set changes — only the stories dir does.
  return `import React from "react";
import { CardErrorBoundary } from "./ErrorBoundary.jsx";

const modules = import.meta.glob("./stories/*.{jsx,tsx}", { eager: true });

const stories = Object.entries(modules)
  .map(([file, mod]) => ({
    name: (mod && mod.title) || file.replace(/^\\.\\/stories\\//, "").replace(/\\.[jt]sx$/, ""),
    Component: mod && mod.default,
  }))
  .filter((s) => typeof s.Component === "function" || (s.Component && typeof s.Component === "object"))
  .sort((a, b) => a.name.localeCompare(b.name));

export function Gallery() {
  return (
    <div style={{ minHeight: "100vh", padding: 24, boxSizing: "border-box" }}>
      <header style={{ marginBottom: 20, fontFamily: "ui-sans-serif, system-ui, sans-serif" }}>
        <div style={{ fontSize: 18, fontWeight: 700 }}>Component preview</div>
        <div style={{ fontSize: 13, opacity: 0.6 }}>
          {stories.length} component{stories.length === 1 ? "" : "s"} rendered in isolation with mock data — the app itself is not running.
        </div>
      </header>
      {stories.length === 0 && (
        <div style={{ opacity: 0.6, fontFamily: "ui-sans-serif, system-ui, sans-serif" }}>
          No previewable components were generated for this change.
        </div>
      )}
      <div style={{ display: "grid", gap: 20 }}>
        {stories.map(({ name, Component }) => (
          <section key={name} style={{ border: "1px solid #e5e7eb", borderRadius: 12, overflow: "hidden" }}>
            <div style={{ padding: "8px 12px", fontSize: 12, fontWeight: 600, fontFamily: "ui-monospace, monospace", background: "#f9fafb", borderBottom: "1px solid #e5e7eb" }}>
              {name}
            </div>
            <div style={{ padding: 16 }}>
              <CardErrorBoundary>
                <Component />
              </CardErrorBoundary>
            </div>
          </section>
        ))}
      </div>
    </div>
  );
}
`;
}

/**
 * Build the harness skeleton (everything except the per-component stories, which
 * are generated separately under `stories/`). Pure — returns the files to write.
 */
export function buildHarnessFiles(args: BuildHarnessArgs): HarnessFile[] {
  const { toolchain, workspacePath, port } = args;
  const globalCssAbs = toolchain.globalCss.map((rel) => path.join(workspacePath, rel));

  return [
    { path: "package.json", content: `${JSON.stringify(HARNESS_PACKAGE_JSON, null, 2)}\n` },
    { path: "vite.config.js", content: viteConfig(workspacePath, port) },
    { path: "index.html", content: indexHtml() },
    { path: "src/main.jsx", content: mainJsx(globalCssAbs) },
    { path: "src/gallery.jsx", content: galleryJsx() },
    { path: "src/ErrorBoundary.jsx", content: errorBoundaryJsx() },
  ];
}

/** The directory (relative to the harness root) where generated stories live. */
export const STORIES_DIR = "src/stories";
